[package]
name = "pyxel-engine"
version = "2.3.18"
authors = ["Takashi Kitao <takashi.kitao@gmail.com>"]
edition = "2021"
description = "Core engine for Pyxel, a retro game engine for Python"
repository = "https://github.com/kitao/pyxel"
license = "MIT"
keywords = ["game", "gamedev", "python"]
categories = ["game-engines", "graphics", "multimedia"]

[lib]
name = "pyxel"

[[test]]
name = "tests"
path = "tests/test_pyxel.rs"
harness = false

[dependencies]
cfg-if = "1.0"
directories = "6.0"
gif = "0.13"
glow = "0.16"
hound = "3.5"
image = "0.25"
indexmap = "2.7"
noise = "0.9"
parking_lot = "0.12"
pyxel-platform = { path = "../pyxel-platform", version = "2.3.18" }
rand = "0.9"
rand_xoshiro = "0.7"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"
toml = "0.8"
zip = { version = "2.2", default-features = false, features = ["deflate"] }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
chrono = "0.4"
